# Change these first
owner: W4L33D # Your GitHub organization or username, where this repository lives
repo: DGIURLs # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 9 * * *"

sites:
  - name: AnsattPortal
    url: https://ansattportal.dgi.no/
  - name: Gardemoregionen
    url: https://gardermoregionen.no/
  - name: Gjerdrum Kommunetv
    url: https://Gjerdrum.kommunetv.no
  - name: Hurdal Kommunetv
    url: https://Hurdal.kommunetv.no
  - name: Mingat DGI
    url: https://mingat.dgi.no/GatGoDGI/api/v1/ping
  - name: Mingat Eidsvoll
    url: https://mingat.dgi.no/GatGoEid/api/v1/ping
  - name: Mingat Gjerdrum
    url: https://mingat.dgi.no/GatGoGje/api/v1/ping
  - name: Mingat Hurdal
    url: https://mingat.dgi.no/GatGoHur/api/v1/ping
  - name: Mingat Nannestad
    url: https://mingat.dgi.no/GatGoNan/api/v1/ping
  - name: Mingat Nes
    url: https://mingat.dgi.no/GatGoNes/api/v1/ping
  - name: Mingat Orb
    url: https://mingat.dgi.no/GatGoOrb/api/v1/ping
  - name: Nannestad Kommunetv
    url: https://Nannestad.kommunetv.no
  - name: Nes Kommunetv
    url: https://nes.kommunetv.no
  - name: Portal Digirom
    url: https://portal2.dgi.no
  - name: Edisvoll Kommune
    url: https://www.Eidsvoll.kommune.no/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /DGIURLs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DGIURLs
  introTitle: "Monitored URL endpoints for DGI"
  introMessage: All endpoint monitoring enabled are shown on this webpage. URL status is updated every day at 09:00, while response time is recorded every 6 hour. The response time graph is updated once each day.
  navbar:
    - title: Status
      href: /
    - title: AzureDevops
      href: https://dev.azure.com/SopraSteria-DPSOManagedServices/RightControl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
